name: Lost Ark Server Check v1
 
on:
  schedule:
    - cron: "0,3,6,9,12,15,18,21,24,27,30,33,36,39,42,45,48,51,54,57 * * * 3" # chạy mỗi 5 phút vào thứ 3, 4
  workflow_dispatch: # cho phép chạy thủ công

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: node check.js --once
